\echo drop table if exists breev_userprofile cascade;
      drop table if exists breev_userprofile cascade;

\echo drop table if exists auk_artikel              cascade;
      drop table if exists auk_artikel              cascade;
\echo drop table if exists breev_userprofile        cascade;
      drop table if exists breev_userprofile        cascade;
\echo drop table if exists urp_roles                cascade;
      drop table if exists urp_roles                cascade;
\echo drop table if exists urp_user_role            cascade;
      drop table if exists urp_user_role            cascade;
\echo drop table if exists auk_krant                cascade;
      drop table if exists auk_krant                cascade;
\echo drop table if exists auk_rubriek              cascade;
      drop table if exists auk_rubriek              cascade;
\echo drop table if exists auk_categorie            cascade;
      drop table if exists auk_categorie            cascade;
\echo drop table if exists auk_gebruiker_categorie  cascade;
      drop table if exists auk_gebruiker_categorie  cascade;
\echo drop table if exists auk_rubriek_categorie    cascade;
      drop table if exists auk_rubriek_categorie    cascade;
\echo drop table if exists auk_artikel_categorie    cascade;
      drop table if exists auk_artikel_categorie    cascade;
\echo drop table if exists auk_artikel_publicatie   cascade;
      drop table if exists auk_artikel_publicatie   cascade;
\echo drop table if exists sar_ignorewordlist       cascade;
      drop table if exists sar_ignorewordlist       cascade;
\echo drop table if exists sar_wordlist             cascade;
      drop table if exists sar_wordlist             cascade;
\echo drop table if exists sar_wordlocation         cascade;
      drop table if exists sar_wordlocation         cascade;
